name: al_mostashar_lawyer
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.2+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  # '>=2.19.6 <3.0.0'
  # '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # get: ^4.6.5
  # smooth_page_indicator: ^1.0.0+2
  # flutter_screenutil: ^5.6.0
  # dio: ^4.0.6
  # dio_http_cache: ^0.3.0
  # audio_wave: ^0.1.4
  # sqflite: ^2.2.6
  # # voice_message_package: ^1.0.41
  # shared_preferences: ^2.0.15
  # flutter_svg: ^1.1.6
  # intl: ^0.17.0
  # lottie: ^2.1.0
  # modal_bottom_sheet: ^2.1.2
  # flutter_slidable: ^3.1.0
  # flutter_countdown_timer: ^4.1.0
  # audioplayers: ^3.0.1
  # im_stepper: ^1.0.1+1
  # blurry_modal_progress_hud: ^1.0.3
  # flutter_spinkit: ^5.1.0
  # file_picker: ^5.2.4
  # rate: ^0.0.2
  # cached_network_image: ^3.2.3
  # shimmer: ^2.0.0
  # fluttertoast: ^8.2.6
  # dropdown_button2: ^2.1.0
  # flutter_progress_hud: ^2.0.2
  # image_picker: ^0.8.7+4
  # firebase_core: ^2.10.0
  # cloud_firestore: ^4.5.3
  # firebase_messaging: ^14.4.1
  # firebase_storage: ^11.1.1
  # flutter_local_notifications: ^14.0.0+1
  # permission_handler: ^10.2.0
  # flutter_sound: ^9.2.13
  # url_launcher: ^6.1.8
  # path_provider: ^2.0.15
  # flutter_cached_pdfview: ^0.4.2
  # http: ^0.13.6
  # awesome_notifications: ^0.7.4+1
  # voice_message_package: ^1.0.41
  # badges: ^3.1.1
  # ntp: ^2.0.0
  # animate_do: ^3.0.2
  # connectivity_plus: ^4.0.1
  # otp_text_field: ^1.1.3
  # googleapis_auth: ^1.4.1

  get: ^4.6.6
  smooth_page_indicator: ^1.2.0+3
  flutter_screenutil: ^5.9.3
  dio: ^5.5.0+1
  # dio_http_cache: ^0.3.0
  audio_wave: ^0.1.5
  sqflite: ^2.3.3+1
  # voice_message_package: ^1.0.41
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  lottie: ^3.1.2
  modal_bottom_sheet: ^3.0.0
  flutter_slidable: ^3.1.1
  flutter_countdown_timer: ^4.1.0
  audioplayers: ^6.0.0
  im_stepper: ^1.0.1+1
  blurry_modal_progress_hud: ^1.1.1
  flutter_spinkit: ^5.2.1
  file_picker: ^8.0.6
  rate: ^0.0.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.6
  dropdown_button2: ^2.3.9
  flutter_progress_hud: ^2.0.2
  image_picker: ^1.1.2
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.2
  flutter_local_notifications: ^17.2.1+2
  permission_handler: ^11.3.1
  flutter_sound: ^9.9.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  flutter_cached_pdfview: ^0.4.2
  http: ^1.2.2
  awesome_notifications: ^0.9.3+1
  voice_message_package: ^2.2.1
  badges: ^3.1.2
  ntp: ^2.0.0
  animate_do: ^3.3.4
  connectivity_plus: ^6.0.4
  otp_text_field: ^1.1.3
  googleapis_auth: ^1.6.0

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo2.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo.png
    - assets/logo2.jpg

 
  fonts:
    - family: tajwal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
